### ISSUE TITLE
"metadata.t7" not find

### ISSUE THREAD

**Issue by 823639792** [art-programmer/FloorNet#4]
@KoykL @art-programmer 
根据RecordWriterTango.py我想将我的数据写入到tfrecords中，并进行评估，但是我不知道metadata.t7（writeExample）是哪里来的，是其机器学习到中间结果吗？是用来将点云转化为俯视图到吗？

According to RecordWriterTango.py I want to write my data into tfrecords and evaluate it, but I don't know where the metadata.t7(in writeExample) comes from, is its machine learning intermediate results?Is it used to turn a point cloud into a top view?

**Comment by art-programmer** [comment]
It is the metadata coming with the annotation, and it is used to convert the point cloud to top-down view. The point cloud is always Z-axis aligned (negative Z is the gravity direction) and the XOY rotation angle in the metadata is used to rotate the point cloud so that it aligned with X-axis and Y-axis (Manhattan World Assumption).
